const allQuestions = [
  "He follado en el instituto/facultad",
  "He salido en el periódico",
  "Me he metido o he intentado meterme algo por el culo",
  "Me he imaginado, sin querer, teniendo sexo con alguien que tenía delante",
  "He querido tener algo con algunx de lxs presentes",
  "Me he imaginado a algunx de lxs presentes desnudx",
  "He salido de fiesta solo para follar",
  "Me he follado a un/a facha",
  "He sentido algo por un/a amigx cercanx",
  "Me he sentido atraídx por alguien que me llevaba más de 20 años",
  "He cagado en la ducha",
  "He hecho un chupón",
  "He recibido un chupón",
  "He fumado maría",
  "He follado en la cama de mis padres/suegros",
  "He estado con alguien que tenía pareja",
  "Me he pintado las uñas",
  "Me he depilado el culo",
  "He tenido un fetiche que me avergonzaba",
  "He follado en una encimera",
  "He tomado la píldora del día después",
  "Me he comido un helado a mordiscos",
  "He salido con alguien menor que yo",
  "He follado con alguien menor de edad siendo yo mayor",
  "He enviado nudes",
  "He sido rechazadx",
  "He follado sin condón",
  "He fingido un orgasmo",
  "He tenido sexo anal",
  "He seguido Operación Triunfo",
  "He sido infiel",
  "Me he sentido sexualmente atraídx por un/a familiar",
  "He querido casarme",
  "He querido tener hijos",
  "He viajado fuera del continente",
  "He vivido un año en el extranjero",
  "He pensando en cambiarme el nombre",
  "Me he enganchado a una serie que sabía que era mala",
  "He probado drogas duras",
  "He tenido sexo en la calle",
  "Me he sacado los mocos delante de mi pareja",
  "He cagado delante de mi pareja",
  "Me he meado de la risa",
  "He dormido en el baño de la facultad",
  "He perdonado una infidelidad",
  "He contemplado el suicidio",
  "He subido una historia para que la viese alguien en concreto",
  "He ido en transporte público sin comprar el billete",
  "Me he enamorado a primera vista",
  "He comprado un animal",
  "He adoptado un animal",
  "He tenido lagartos",
  "He entrado en la dark web",
  "He visto una película porno",
  "Me he hecho un cristo en el pelo",
  "He provocado a mi pareja en público",
  "Me he liado con alguien de mi mismo sexo",
  "He tenido un juguete sexual",
  "He dejado una carrera",
  "Me he tomado un año sabático",
  "Me han preparado una fiesta sorpresa",
  "He pensado en raparme",
  "He querido tener pareja solo para hacer planes en Navidad",
  "He ido a terapia",
  "Me he operado",
  "He sido veganx/vegetarianx",
  "He follado en un lugar público de día",
  "He follado con alguien de mi mismo sexo",
  "He consumido cocaína",
  "He consumido popper",
  "He vomitado en la cama",
  "Me he arrastrado por alguien",
  "He consumido drogas en un concierto/festival",
  "He tenido ropa de marca",
  "He jugado al Fornite",
  "He jugado a League of Legends",
  "Me he sentido confusx con mi género",
  "He vuelto con mi ex",
  "He dudado de mi sexualidad por culpa de un/a ex",
  "He follado esta semana",
  "He follado este mes",
  "He resuelto un cubo de Rubik",
  "He tenido Tinder/Grindr",
  "He probado alucinógenos",
  "He sido adictx a un medicamento",
  "He follado en un coche",
  "Me he sentido atraídx por la pareja o expareja de mi hermano",
  "Me he enamorado",
  "He querido acabar con el sistema capitalista",
  "He apagado las noticias porque me estaban amargando",
  "He follado con un/a amigx cercanx",
  "He disfrutado de algún tipo de daño o dolor físico",
  "Me he tirado a un skater",
  "He sentido atracción hacia C. Tangana",
  "Me he tocado pensando en alguien famoso",
  "He pensado en una persona distinta de con quien estaba follando",
  "Me ha puesto la idea de una persona que me gusta follando con otra",
  "Me he sentido atraídx sexualmente por una voz",
  "He comprado un test de embarazo",
  "No he sentido que se corrían dentro de mí",
  "He creado a la persona que me gustaba en los Sims",
  "He tenido Habbo",
  "He tenido una relación a distancia",
  "He tenido una pareja tóxica",
  "He probado drogas más fuertes que la marihuana",
  "Me he arrepentido de tener sexo con alguien",
  "Me he sentido atraídx por alguien mucho menor que yo",
  "He follado en la ducha",
  "He pensado que follar en la ducha está sobrevalorado",
  "He follado en el coche solo por el morbo",
  "He ido a clase fumadx",
  "He recibido un beso negro",
  "He dado un beso negro",
  "Me he enamorado de un personaje de ficción",
  "He tenido vídeos ridículos míos en YouTube",
  "He buscado mi nombre en Google",
  "Me he grabado follando",
  "He jugado al Zelda",
  "He preferido a Bulbasur",
  "He ido a un concierto de rap",
  "Me he encontrado a un/a famosx por la calle",
  "He escrito una carta de amor",
  "No he ido a votar pudiendo",
  "Me ha importado el tamaño",
  "He sentido asco al besar a alguien",
  "Me he tirado a alguien porque me recordaba a otra persona",
  "He tenido sexo con una persona que en ese momento no me parecía muy guapa",
  "Me he blanqueado el ano",
  "Me han hecho daño practicando sexo oral",
  "He estado interesado en prácticas sexuales que incluyen pis",
  "Me han puesto los pies",
  "Le he mandado un nude a alguien que no era mi pareja",
  "He tenido envidia insana de un/a amigx",
  "He robado dinero a mis padres",
  "Le he perreado a un/a desconocidx",
  "He montado un espectáculo en clase",
  "Me he tocado pensando en algunx de lxs presentes",
  "He usado juguetes sexuales",
  "He ido a esquiar",
  "Me he sabido bien las conjugaciones verbales",
  "He arrancado los pétalos de una flor para ver si sí o si no",
  "He llorado en las últimas 24h",
  "He follado en el último mes",
  "He pagado por sexo",
  "Me he olido la mano después de rascarme el culo",
  "Me he lamido el codo",
  "Me he planteado seriamente dejar lo que estoy estudiando ahora mismo",
  "He llorado por algunx de lxs presentes",
  "He puesto una excusa para no quedar con algunx de lxs presentes",
  "He querido cambiarme por alguien no famoso",
  "Lo he hecho en un parque",
  "Me he planteado poner los cuernos",
  "He usado nata en un ámbito sexual",
  "Le he meado en la cara a alguien",
  "He deseado que me cagasen en el pecho",
  "Me he mirado el ano en el espejo",
  "Me he mirado los genitales en el espejo",
  "Me he masturbado en una piscina",
  "Me he masturbado pensando en el padre/madre de un/a amigx",
  "He mentido en este yo nunca",
  "Me he masturbado pensando en un/a profesor/a",
  "Me he sentido atraídx por mi mejor amigx",
  "Le he robado maría a mi compañerx de piso",
  "He follado sin condón",
  "He estornudado y el moco le ha dado a alguien",
  "He tenido lagunas post *discoteca de tu ciudad/pueblo*",
  "He hecho un trío con algunx de lxs presentes",
  "Me he imaginado follando con algunx de lxs presentes",
  "He fingido quedarme dormidx para no ir a clase",
  "He usado juguetes sexuales con alguien",
  "He tenido semen en la ropa",
  "He probado el semen",
  "He cancelado planes con mis amigxs para follar",
  "He dormido completamente desnudx con alguien",
  "He pensado que soy más inteligente que otra persona",
  "He ido de cruising",
  "Me he puesto a comprar por internet para tranquilizarme",
  "Me he olvidado de algo que había pedido por internet",
  "Me he aguantado las ganas de cagar hasta llegar a casa",
  "He pagado por porno",
  "Me he pasado más de dos horas seguidas viendo porno",
  "He cagado de campo",
  "Me he dormido en clase",
  "He salido de \"de tranquis\" y he llegado a casa de día",
  "Me he comido un chicle que se me había caído al suelo",
  "Me he olvidado de tender la ropa limpia de la lavadora",
  "He llegado tarde a trabajar",
  "He sido humillado por un profesor",
  "He pensado en solucionar mis problemas durmiendo",
  "He sentido celos",
  "He hecho solamente la portada de un trabajo",
  "He bebido alcohol estando solo",
  "He tenido fetiches raros",
  "He pasado una frontera llevando droga escondida",
  "Me he tirado un pedo y he culpado a otrx",
  "Me quedado con las ganas",
  "Me he encontrado un pelo en la boca después de practicar sexo oral",
  "Me habría tirado a alguien a principio de curso pero ahora me da asco",
  "Me he liado con un/a profesor/a",
  "He hecho topless",
  "Me he rapado",
  "Me he cortado el pelo a mí mismx",
  "Le he cortado el pelo a alguien",
  "Me he colado en una casa en construcción",
  "He montado en helicóptero",
  "Le he dicho a alguien que le quería sin sentirlo",
  "Me he sentido atraíxo hacia la pareja de un/a amigx",
  "Me he tirado a mi crush estando borrachx y no me acordaba de nada a la mañana siguiente",
  "Me he subido a un árbol borracho",
  "He roto algo y me he hecho el/la locx",
  "Me he perdido una polla por estar rezando",
  "He soñado con algunx de lxs presentes",
  "He pasado más de una semana sin cambiarle el líquido a las lentillas",
  "He utilizado \"estornocleidomastoideo\" jugando al ahorcado",
  "Me he liado con alguien que tenía pareja",
  "He estado más de siete días sin ducharme",
  "Me he callado una ficha perfecta por vegüenza",
  "Me he imaginado sin querer teniendo relaciones con un/a familiar",
  "He escuchado reggaeton en secreto",
  "He hecho una playlist para follar",
  "He fingido durante el sexo",
  "Me he imagino a algunx de lxs presentes desnudx",
  "Me he liado con un/a familiar",
  "Le he robado algo a algún/alguna amigx",
  "He pillado a mi pareja/alguien mirandome el móvil",
  "Me ha tirado fichas las pareja de un/a amigx",
  "Me he masturbado con la regla",
  "Me han comido el coño teniendo la regla",
  "He tenido problemas para mojarme",
  "He tenido un gatillazo",
  "Me he liado con alguien en *lugar típico de tu zona*",
  "Le he mangado la copa a alguien",
  "He copiado en un examen de lo que estoy estudiando ahora",
  "He hecho un deporte de riesgo",
  "Lo he hecho en un bus en marcha",
  "He pensado que algunx de lxs presentes folla de puta madre",
  "Le he dicho a un/a amigx que es guapx por compromiso",
  "He fantaseado con algunx de lxs presentes",
  "Le he potado encima a alguien",
  "He pillado a mis padres follando",
  "He pensado que algunx de lxs presentes es fex",
  "He hablado mal de algunx de lxs presentes",
  "Me he meado en la cama soñando que estaba en el baño",
  "He follado con el/la familiar de un/a ex",
  "He follado con algunx de lxs presentes",
  "Me he sacado un moco y lo he pegado debajo de la mesa",
  "He follado encima de un electrodoméstico",
  "He jugado a la botella para liarme con alguien",
  "Me he puesto nerviosx en mi primera vez",
  "Me he liado con el/la hermanx de algunx de lxs presentes",
  "He querido pegarle a algunx de lxs presentes",
  "He confundido a mis padres por la calle",
  "Me he emborrachado jugando al yo nunca",
  "He visto a un/a vecinx desnudx",
  "He follado en la cama de mis suegros",
  "He metido mano en el cine",
  "Me he olvidado de que había besado a alguien",
  "He pensado que la persona que está leyendo está cachonda",
  "He beasdo a alguien por pena",
  "He usado un succionador de clítoris",
  "He cagado en un pub",
  "He buceado con tiburones",
  "Me he liado con algunx de lxs presentes",
  "Me he hecho el/la borrachx",
  "He comido pienso",
  "He probado la regla",
  "He hecho balconing",
  "Me he masturbado pensando en mi mejor amigx",
  "Le he dicho a un pavo follando que cambiásemos a por detrás y pensó que quería por el culo",
  "Me he roto el frenillo",
  "He hecho el Mannequin Challenge",
  "He pensado que un cantante era negro y después de ver el vídeo descubrí que era blanco",
  "Me ha dado morbo un personaje de dibujos",
  "He practicado sexo oral mal a propósito",
  "He pensado que mi sexo oral es flawless",
  "He expulsado semen por la nariz",
  "Me han pillado follado",
  "He pensado que la persona de mi derecha tiene pinta de follar bien",
  "He hecho squirting",
  "He practiado fisting",
  "He pensado que me había cagado encima mientras iba puesto de setas",
  "He pensado que el reggaeton antiguo es mejor",
  "He preferido el sexo suave",
  "He preferido el sexo duro",
  "Me he tirado a mi mejor amigx",
  "Me he colado en una piscina",
  "He estado pillado de alguien de aquí",
  "He enviado un nude por error",
  "He dado like sin querer mientras stalkeaba",
  "He pensado que dos persona de este grupo deberían follar",
  "Me ha hecho daño enterarme de algo jugando al yo nunca",
  "He hecho captura a un perfil de Instagram para hacer zoom en la foto de perfil",
  "Le he hablado a mi psicólogx de algunx de lxs presentes",
  "Me he hecho Tinder/Grindr para encontrar a una persona en concreto",
  "Me he chocado contra una farola por estar mirando un perrete",
  "He meado en la calle en un país extranjero",
  "Me he tragado un chicle",
  "He follado durante una clase online",
  "He cagado en un avión",
  "Me he inventado que me lié con algunx de lxs presentes",
  "Me he inventado que me lié con alguien",
  "Me he tirado de un coche en marcha"
];
var questions = [];

const playButton = document.getElementById("play");
const questionParagraph = document.getElementById("question");

function sample(array, size = 1) {
  var sampleSet = new Set();
  for (var i = 0; i < size; i++) {
    var index;
    do {
      index = Math.floor(Math.random() * array.length);
    }
    while (sampleSet.has(index));
    sampleSet.add(index);
  }
  return [...sampleSet].map(i => array[i]);
}

function playClicked() {
  if (!questions.length) {
    questions = sample(allQuestions, 50);
  }
  questionParagraph.innerHTML = questions.pop();
  playButton.textContent = "Siguiente";
}

playButton.addEventListener("click", playClicked, false);
